blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/dougiteixeira/proxmoxve/discussions/new?category=feature-request
    about: Please start a new discussion to request a new feature.
